"""P1c: cross-architecture golden fixtures, plus the end-to-end CLI path.

Spec: docs/design/vidya-pilot-spec.md §17.3 (determinism suite).

**What "cross-architecture" means here.** The values below are pinned constants, generated once on
x86-64 Linux. They are not regenerated by the test -- a test that recomputes its own expectation
proves only that the code agrees with itself. Running this same file unchanged on aarch64 (or any
other target) is the cross-architecture check: if canonical serialization, hashing, sorting, or the
fold's iteration order differ anywhere, a pinned value stops matching.

**Honest status:** executed on x86-64 only so far. The fixture IS the contract; the second
architecture is a matter of running it somewhere else, and until that happens the program handoff
carries P1c as open with this file named as the instrument.

Why the design should be architecture-independent in the first place, and where it could fail
anyway: floats are rejected outright (the one genuinely hard part of JCS number formatting is
therefore unreachable); Python string comparison is by code point and not locale-sensitive; every
collection that reaches a hash is explicitly sorted. The plausible regressions are a dict iteration
order leaking into an output, a locale-dependent sort creeping in, or a Python version changing
`json.dumps` escaping -- all of which these pins would catch.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts" / "vidya"))

import checkpoint as cp  # noqa: E402
from canonical import content_hash  # noqa: E402
from fold import fold  # noqa: E402
from frames import make_frame  # noqa: E402

GOLDEN_AS_OF = "2026-01-01T00:00:00Z"

# ---- pinned on x86-64 Linux, CPython. Do NOT regenerate to make a test pass. ----
GOLDEN_FRAME_IDS = [
    "sha256:71b42263b07e31d57654c4cdf0c479326a5263ff7bfb31e932086d4a32f5ae41",
    "sha256:3ac97cbf9191db1f25aaaa8d723d1b1807cc307301188e1f561b1fa445c99c96",
    "sha256:df483ab44e0bbd898df9e748d7452a03556b201f643775541ac47ac0d04d89ae",
    "sha256:39b19b50e431c54061f35b10e7b4a828de9aea28de96e1df651e0ab776ee1868",
    "sha256:99e30050c9790594ef481d11c9cf0441b67b46c9366eed8c837569add6b4b12b",
]
# fold-version history for this pin. A derived-state SHAPE change must produce a new state
# identity (spec §17.3), so the pin is re-cut deliberately and the reason recorded -- never
# regenerated quietly to make a red test green.
#   0.1.0 -> sha256:8591365a98fb27d9f25a3fc1f64a781293a8a4997cf000860549aacaba534ed1
#   0.2.0 -> current: Belief gained `corrections` and `review_required` (P2c)
GOLDEN_STATE_HASH = "sha256:76eef15c9a5b7f01d6a699312a816577a457bc93c42dae9d6064cec577a59336"
GOLDEN_MERKLE_ROOT = "cea68c9737862e21a50c4fe718b8fbc7ca42d6427b18359c89e05c966b0a2ce5"
GOLDEN_NOTE_HASH = "sha256:ac51c1a0bc1cd76cc77c621bf252c68de5edccc0adadd400947dcc071b69d715"


def _golden_corpus() -> list[dict]:
    """A fixed corpus exercising both axes, both polarities, and a synthetic join."""
    def frame(claim, evidence, q, t, kind="evidence_supports_claim"):
        return make_frame(
            frame_type=f"epyc.vidya/frame/{kind}/v1",
            assertion={"claim_id": claim, "evidence_id": evidence, "grade": {"Q": q, "T": t}},
            provenance={"method": "golden", "anchor": f"anchor:{evidence}"},
            actor="golden/fixture",
            authority_scope="research-verification",
            created_at=GOLDEN_AS_OF,
        )

    return [
        frame("clm-alpha", "evd-1", "Verified", "Located"),
        frame("clm-alpha", "evd-2", "Judged", "Anchored"),      # synthetic join with evd-1
        frame("clm-beta", "evd-3", "Witnessed", "Attested"),
        frame("clm-beta", "evd-4", "Hinted", "Located", "evidence_opposes_claim"),
        frame("clm-gamma", "evd-5", "Judged", "Located"),
    ]


class TestGoldenFixtures:
    def test_frame_ids_match_pins(self):
        got = [f["frame_id"] for f in _golden_corpus()]
        assert got == GOLDEN_FRAME_IDS, (
            "frame identity drifted. Either canonical serialization changed, or this is a "
            "different architecture/interpreter producing different bytes for the same value."
        )

    def test_fold_state_hash_matches_pin(self):
        assert fold(_golden_corpus(), as_of=GOLDEN_AS_OF).state_hash() == GOLDEN_STATE_HASH

    def test_merkle_root_matches_pin(self):
        hashes = [content_hash(f) for f in _golden_corpus()]
        chk = cp.checkpoint_for("golden.test/ledger", hashes)
        assert chk.root_hash.hex() == GOLDEN_MERKLE_ROOT

    def test_checkpoint_note_bytes_match_pin(self):
        hashes = [content_hash(f) for f in _golden_corpus()]
        note = cp.format_checkpoint(cp.checkpoint_for("golden.test/ledger", hashes))
        assert content_hash(note) == GOLDEN_NOTE_HASH

    def test_reordering_independent_frames_preserves_state_hash(self):
        corpus = _golden_corpus()
        assert fold(list(reversed(corpus)), as_of=GOLDEN_AS_OF).state_hash() == GOLDEN_STATE_HASH

    def test_state_hash_is_sensitive_to_the_derived_state_shape(self):
        """The pin must move when the shape moves -- that is what makes it a state IDENTITY.

        This test exists because the 0.1.0 -> 0.2.0 change was caught by a red pin rather than by
        anyone remembering to think about it.
        """
        from fold import Belief  # noqa: PLC0415

        assert {"corrections", "review_required"} <= set(
            Belief(claim_id="x").as_dict()
        ), "belief serialization dropped fields the current pin was cut against"

    def test_golden_corpus_contains_a_synthetic_join(self):
        # Guard the fixture itself: if a future edit makes every claim single-path, the pins would
        # still match while no longer exercising the property they were chosen for.
        b = fold(_golden_corpus(), as_of=GOLDEN_AS_OF).beliefs["clm-alpha"]
        assert len(b.pro_witnesses) == 2, "clm-alpha must keep exercising the synthetic join"


# ------------------------------------------------------------------ CLI e2e

def _cli(*args, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(REPO / "scripts" / "vidya" / "cli.py"), *args],
        capture_output=True, text=True, cwd=cwd,
    )


@pytest.fixture()
def workspace(tmp_path: Path) -> Path:
    (tmp_path / ".vidya").mkdir()
    return tmp_path


class TestCliEndToEnd:
    def _seed(self, workspace: Path) -> Path:
        ledger = workspace / ".vidya" / "ledger.jsonl"
        for i, frame in enumerate(_golden_corpus()):
            path = workspace / f"frame-{i}.json"
            path.write_text(json.dumps(frame))
            res = _cli("--ledger", str(ledger), "append", str(path), cwd=workspace)
            assert res.returncode == 0, res.stderr
        return ledger

    def test_append_fold_verify(self, workspace):
        ledger = self._seed(workspace)
        res = _cli("--ledger", str(ledger), "--json", "fold",
                   "--as-of", GOLDEN_AS_OF, cwd=workspace)
        assert res.returncode == 0, res.stderr
        payload = json.loads(res.stdout)
        assert payload["state_hash"] == GOLDEN_STATE_HASH
        assert payload["frontier"] == 5

        res = _cli("--ledger", str(ledger), "--json", "verify", cwd=workspace)
        payload = json.loads(res.stdout)
        assert res.returncode == 0
        assert payload["chain_ok"] and payload["checkpoints_ok"] and payload["ok"]

    def test_verify_detects_a_tampered_ledger(self, workspace):
        ledger = self._seed(workspace)
        ledger.write_text(ledger.read_text().replace("clm-alpha", "clm-XXXXX"))
        res = _cli("--ledger", str(ledger), "--json", "verify", cwd=workspace)
        payload = json.loads(res.stdout)
        assert res.returncode == 1
        # Content tampering breaks the CHAIN specifically -- the two statuses are separate so a
        # caller can tell "this file is corrupt" from "this file is not the history we published".
        assert not payload["chain_ok"]
        assert any("frame_hash" in p for p in payload["chain_problems"])

    def test_a_recomputed_rewrite_passes_the_chain_and_fails_the_checkpoint(self, workspace):
        """The reason L1 exists: L0 cannot see a rewriter who redoes the chain."""
        ledger = self._seed(workspace)
        res = _cli("--ledger", str(ledger), "checkpoint", "--emit", cwd=workspace)
        assert res.returncode == 0, res.stderr

        # Truncate and fully re-chain -- exactly what a competent tamperer would do.
        sys.path.insert(0, str(REPO / "scripts" / "vidya"))
        from ledger import Ledger  # noqa: PLC0415

        kept = [r.frame for r in Ledger(ledger).read_all()[:-2]]
        ledger.unlink()
        rebuilt = Ledger(ledger)
        for frame in kept:
            rebuilt.append(frame)

        res = _cli("--ledger", str(ledger), "--json", "verify", cwd=workspace)
        payload = json.loads(res.stdout)
        assert payload["chain_ok"], "a recomputed chain is internally consistent -- L0 is blind"
        assert not payload["checkpoints_ok"], "the published checkpoint must catch it"
        assert res.returncode == 1

    def test_fold_requires_an_explicit_as_of(self, workspace):
        ledger = self._seed(workspace)
        res = _cli("--ledger", str(ledger), "fold", cwd=workspace)
        assert res.returncode != 0, "as_of must never be defaulted to now"

    def test_append_rejects_an_invalid_frame(self, workspace):
        bad = workspace / "bad.json"
        bad.write_text(json.dumps({"frame_type": "not-a-versioned-uri"}))
        res = _cli("--ledger", str(workspace / ".vidya" / "ledger.jsonl"),
                   "append", str(bad), cwd=workspace)
        assert res.returncode != 0
