"""EVL-46 (TU-DTAP-1): disposable local runner for a bounded, reviewed subset of
DecodingTrust-Agent (DTAP) benchmark cases.

Subset provenance: https://github.com/AI-secure/DecodingTrust-Agent @ commit
e0323a521ba4ef88f8e14c1eccf68d0a3d19a458 (tree fd5a107aedb8971c346fc0e85d4789bf510e3f5f),
Apache-2.0. See ../../manifest.json, ../../cases.json and ../../README.md.

Design constraints (per handoffs/active/tool-use-eval-contract.md TU-DTAP-1):
  * zero upstream dependencies, zero inference in tests (dry-run stub),
  * transcribed configs + deterministic final-state judges preserved,
  * immutable hash-chained trace replay,
  * typed failure outcomes from exactly
    model|parser|tool|endpoint|harness|judge|infrastructure|overflow,
  * per-arm fixed configuration (model/prompt/tools/temperature/retries/harness),
  * repeated seeds with Wilson confidence intervals,
  * attack-generation target-disjoint from the final comparison (injected
    payloads are fixed released constants; the harness never optimizes attacks).
"""
from __future__ import annotations

from pathlib import Path

# Transcribed task registry (upstream config.yaml -> JSON), generated by
# tools/transcribe.py from the pinned upstream commit.
REGISTRY_PATH = Path(__file__).resolve().parent.parent / "cases.json"

