#!/mnt/raid0/llm/epyc-inference-research/.venv/bin/python
"""Q38-T7 rescore, task 1: is the INF-70 `uniq < 0.35` trigger length-biased on KNOWN-COHERENT text?

No inference. Tokenizes local text with the Qwen3.8-27B tokenizer.json (the same vocabulary the
27B server's /tokenize uses) and measures uniq = |set(ids)| / n on prefixes of growing length.

Corpora (all known-coherent, none generated by the system under test):
  handoff   /workspace/handoffs/active/*.md (human/agent-written markdown)
  wiki      /workspace/wiki/*.md
  reasoning Qwen-27B-family thinking traces (architect-27b A3-tc raw capture, swebench_oracle)
  ctx       the C1..C7 planner contexts Phase B prompts are cut from
  phaseA    the 17 COHERENT Phase-A text_heads (dflash2 arm) concatenated (only 160 chars each are stored)

Writes length_bias.json + prints a table: per corpus x prefix length, the median / p10 / min uniq and
the share of documents that v1 (uniq < 0.35) would flag SALAD. Also fits Heaps' law V = K n^beta.
"""
import glob
import json
import math
import statistics
from pathlib import Path

from tokenizers import Tokenizer

TOK = Tokenizer.from_file("/mnt/raid0/llm/models/turboderp/Qwen3.8-27B-exl3-4.00bpw/tokenizer.json")
OUT = Path(__file__).resolve().parent
LENGTHS = [100, 200, 300, 500, 800, 1000, 1200, 1500, 2000]
RAW = ("/mnt/raid0/llm/tmp/standalone-v3-probe.UhfAMX/artifacts/architect-27b-finetunes-v8-20260726/"
       "expanded-six-arm-v4-tail-replay-20260727/A3-tc/raw_capture.sealed.jsonl")
CALLS = ("/mnt/raid0/llm/tmp/gpu-block-27b-20261003/results/q38_t7/20261004T025247Z/calls.jsonl")


def ids(text: str) -> list[int]:
    return TOK.encode(text, add_special_tokens=False).ids


def corpora() -> dict[str, list[tuple[str, list[int]]]]:
    c: dict[str, list[tuple[str, list[int]]]] = {}
    c["handoff"] = [(p, ids(Path(p).read_text(errors="ignore"))) for p in sorted(glob.glob("/workspace/handoffs/active/*.md"))]
    c["wiki"] = [(p, ids(Path(p).read_text(errors="ignore"))) for p in sorted(glob.glob("/workspace/wiki/*.md"))]
    rs = []
    for line in open(RAW):
        d = json.loads(line)
        r = d.get("reasoning") or ""
        if len(r) > 4000:
            rs.append((f"{d['id']}#rep{d.get('rep')}", ids(r)))
    c["reasoning"] = rs
    c["ctx"] = [(p, ids(Path(p).read_text(errors="ignore")))
                for p in sorted(glob.glob("/mnt/raid0/llm/tmp/ds41-c95/contexts/C*/prompt.inline.txt"))]
    heads = [json.loads(l) for l in open(CALLS)]
    heads = [r["text_head"] for r in heads if r.get("phase") == "A" and r.get("arm") == "dflash2"
             and r["coherence"]["cls"] == "COHERENT"]
    c["phaseA"] = [("phaseA_concat", ids("\n\n".join(heads)))]
    return c


def heaps_fit(seqs: list[list[int]]) -> tuple[float, float]:
    """Least squares on log V(n) = log K + beta log n over prefixes 50..2000 of every doc."""
    xs, ys = [], []
    for s in seqs:
        seen: set[int] = set()
        for i, t in enumerate(s[:2000], 1):
            seen.add(t)
            if i >= 50 and i % 25 == 0:
                xs.append(math.log(i))
                ys.append(math.log(len(seen)))
    mx, my = statistics.fmean(xs), statistics.fmean(ys)
    beta = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sum((x - mx) ** 2 for x in xs)
    return math.exp(my - beta * mx), beta


def main() -> None:
    c = corpora()
    table = {}
    print(f"{'corpus':10} {'n':>5} {'docs':>4} {'median':>7} {'p10':>6} {'min':>6} {'v1 SALAD %':>10}")
    for name, docs in c.items():
        table[name] = {}
        for n in LENGTHS:
            us = [len(set(s[:n])) / n for _, s in docs if len(s) >= n]
            if not us:
                continue
            us.sort()
            row = {"docs": len(us), "median": round(statistics.median(us), 3),
                   "p10": round(us[max(0, int(0.1 * len(us)) - 1)], 3) if len(us) >= 5 else None,
                   "min": round(us[0], 3), "v1_salad_share": round(sum(u < 0.35 for u in us) / len(us), 3)}
            table[name][n] = row
            print(f"{name:10} {n:>5} {row['docs']:>4} {row['median']:>7} {str(row['p10']):>6} {row['min']:>6} "
                  f"{100 * row['v1_salad_share']:>9.0f}%")
    K, beta = heaps_fit([s for docs in c.values() for _, s in docs if len(s) >= 300])
    Kr, br = heaps_fit([s for _, s in c["reasoning"]])
    print(f"\nHeaps fit, all corpora: V = {K:.2f} n^{beta:.3f}; reasoning only: V = {Kr:.2f} n^{br:.3f}")
    # word counts at the v1 crossing, for the "800 words" framing
    w800 = []
    for name in ("handoff", "wiki", "reasoning"):
        for _, s in c[name]:
            if len(s) >= 1500:
                text = TOK.decode(s[:1500])
                w800.append(len(text.split()))
    print(f"words per 1500 tokens (median over docs >= 1500 tok): {statistics.median(w800):.0f}")
    (OUT / "length_bias.json").write_text(json.dumps(
        {"tokenizer": "Qwen3.8-27B tokenizer.json", "table": table,
         "heaps_all": {"K": round(K, 3), "beta": round(beta, 4)},
         "heaps_reasoning": {"K": round(Kr, 3), "beta": round(br, 4)},
         "words_per_1500_tokens_median": statistics.median(w800),
         "docs": {k: len(v) for k, v in c.items()}}, indent=1))


if __name__ == "__main__":
    main()
