#!/usr/bin/env python3
"""Generate the opencode ``permission.bash`` deny block from the scanner's
canonical tables — never hand-edit the permission block again (INC-20260823
built the guard in two surfaces with duplicated hand-written rules; a second
hand-edited copy is drift by construction).

SOURCE OF TRUTH: ``filesystem_containment_scan.py`` — its module-level tables
(``_CLASS_A_VERBS``, ``_PKG_TOOLS``/``_PKG_ACTIONS``/``_DPKG_INSTALL_FLAGS``,
the write-verb tables, ``_RAW_ROOTS``) exported via ``rules_dump()`` (CLI:
``--dump-rules``). This generator consumes that export and nothing else.

WHAT IS GENERATED, AND WHY IT IS AN OVER-APPROXIMATION BY DESIGN:

  * For every CLASS A verb: ``"<verb>*": "deny"`` and ``"sudo <verb>*": "deny"``.
  * ``"mkfs*"`` (the scanner refuses any ``mkfs*`` base), then for the package
    tools every refused action: ``"apt install*"``, ``"apt purge*"``,
    ``"apt-get autoremove*"``, ... and the dpkg flags: ``"dpkg -i*"``,
    ``"dpkg --install*"``, ... ; finally ``"dd of=/dev/*"``.

  opencode permission patterns are literal-prefix globs against the command
  string, so ``sudo -n mount ...`` slips past ``"sudo mount*"`` and
  ``dd of=/dev/null`` is over-denied by ``"dd of=/dev/*"``. These patterns are
  DEFENSE-IN-DEPTH for the unambiguous literals; the real gate — the one with
  runner-skipping, path resolution, the allowlist and EPYC_FS_ACK — is the
  scanner behind the opencode plugin (``.opencode/plugins/
  filesystem-containment.ts``). The permission block therefore NEVER carries
  the containment roots or the allowlist: those cannot be expressed as deny
  patterns without a second, drifting rule table.

MODES:

  * ``--write-project`` — regenerate /workspace/opencode.json (preserves
    ``$schema`` and every other top-level key).
  * ``--write-global`` — regenerate ~/.config/opencode/opencode.jsonc
    (preserves the comment header and other keys; needed for lane-worktree
    coverage, since worktrees have no .opencode/ of their own).
  * ``--check`` — exit 1 if either file's permission block differs from what
    would be generated (the parity gate); exit 0 when both are in sync.

DETERMINISM: output order follows the dump: sorted verbs (frozensets have no
order), the mkfs prefix, sorted pkg tools/actions, the dpkg flag tuple in its
source order, then dd.

Tests: scripts/hooks/tests/test_harness_guard_parity.py.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import filesystem_containment_scan as fs  # noqa: E402 — the ONE truth

PROJECT_CONFIG = Path("/workspace/opencode.json")
GLOBAL_CONFIG = Path.home() / ".config" / "opencode" / "opencode.jsonc"
SCHEMA_URL = "https://opencode.ai/config.json"

FRESH_GLOBAL_COMMENTS = [
    "  // GENERATED by scripts/hooks/generate_opencode_permissions.py — do not hand-edit.",
    "  // permission rules derive from scripts/hooks/filesystem_containment_scan.py",
    "  // (the ONE source of truth; --check flags any drift).",
    "  // Config is loaded at opencode start: RESTART opencode after changing this.",
]


def bash_deny_patterns(tables: dict | None = None) -> list[str]:
    """Ordered deny patterns, derived ONLY from the scanner's canonical tables."""
    t = tables if tables is not None else fs.rules_dump()
    out: list[str] = []
    verbs = [v for v in t["class_a_verbs"]]
    if t.get("mkfs_prefix") and t["mkfs_prefix"] not in verbs:
        verbs.append(t["mkfs_prefix"])
    for verb in verbs:
        out.append(f"{verb}*")
        out.append(f"sudo {verb}*")
    for tool in t["pkg_tools"]:
        if tool == "dpkg":
            continue  # dpkg mutates via flags, not actions — handled below
        for action in t["pkg_actions"]:
            out.append(f"{tool} {action}*")
    for flag in t["dpkg_install_flags"]:
        out.append(f"dpkg {flag}*")
    out.append("dd of=/dev/*")
    return out


def permission_block(tables: dict | None = None) -> dict:
    """The opencode ``permission`` value: {"bash": {pattern: "deny", ...}}."""
    return {"bash": {p: "deny" for p in bash_deny_patterns(tables)}}


def project_config_text(existing: dict | None = None, tables: dict | None = None) -> str:
    """Full text of /workspace/opencode.json, permission block replaced."""
    existing = existing if isinstance(existing, dict) else {}
    out: dict = {}
    if "$schema" not in existing:
        out["$schema"] = SCHEMA_URL
    for key, value in existing.items():
        out[key] = permission_block(tables) if key == "permission" else value
    if "permission" not in existing:
        out["permission"] = permission_block(tables)
    return json.dumps(out, indent=2) + "\n"


def _comment_lines(text: str) -> list[str]:
    """Raw ``//`` comment lines (line-start after whitespace), in file order."""
    out = []
    for line in text.splitlines():
        if line.lstrip().startswith("//") or line.lstrip().startswith("/*"):
            out.append(line.rstrip("\n"))
    return out


def _strip_comments(text: str) -> str:
    return "\n".join(
        line for line in text.splitlines()
        if not (line.lstrip().startswith("//") or line.lstrip().startswith("/*"))
    )


def global_config_text(existing: str | None = None, tables: dict | None = None) -> str:
    """Full text of the global opencode.jsonc: comment header + other keys
    preserved, permission block replaced. Comments are kept in their original
    order and reinserted right after the $schema line (the canonical spot)."""
    comments = _comment_lines(existing) if existing else list(FRESH_GLOBAL_COMMENTS)
    existing_obj = None
    if existing:
        try:
            existing_obj = json.loads(_strip_comments(existing))
        except json.JSONDecodeError:
            existing_obj = None  # unparseable file: regenerate from scratch
    body = project_config_text(existing_obj, tables).splitlines()
    out = []
    for line in body:
        out.append(line)
        if line.strip().startswith('"$schema"'):
            out.extend(comments)
    return "\n".join(out) + "\n"


def check(tables: dict | None = None) -> int:
    """0 = both configs byte-match their freshly generated form; 1 = drift."""
    ok = True
    for name, path, gen in (
        ("project  /workspace/opencode.json", PROJECT_CONFIG,
         project_config_text(_read_json(PROJECT_CONFIG), tables)),
        ("global   ~/.config/opencode/opencode.jsonc", GLOBAL_CONFIG,
         global_config_text(_read_text(GLOBAL_CONFIG), tables)),
    ):
        on_disk = _read_text(path)
        if on_disk is None or on_disk != gen:
            print(f"[drift] {name} differs from the generated permission block — "
                  f"run: python3 scripts/hooks/generate_opencode_permissions.py "
                  f"--write-project --write-global", file=sys.stderr)
            ok = False
    return 0 if ok else 1


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def _read_json(path: Path) -> dict | None:
    text = _read_text(path)
    if text is None:
        return None
    try:
        data = json.loads(text)
        return data if isinstance(data, dict) else None
    except json.JSONDecodeError:
        return None


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    wrote = False
    if "--write-project" in argv:
        PROJECT_CONFIG.parent.mkdir(parents=True, exist_ok=True)
        PROJECT_CONFIG.write_text(project_config_text(_read_json(PROJECT_CONFIG)),
                                  encoding="utf-8")
        wrote = True
    if "--write-global" in argv:
        GLOBAL_CONFIG.parent.mkdir(parents=True, exist_ok=True)
        GLOBAL_CONFIG.write_text(global_config_text(_read_text(GLOBAL_CONFIG)),
                                 encoding="utf-8")
        wrote = True
    if "--check" in argv:
        return check()
    if wrote:
        return 0
    print("usage: generate_opencode_permissions.py "
          "[--write-project] [--write-global] [--check]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
