#!/bin/bash
set -euo pipefail
# Install the pre-commit wrapper into every owned repo. Idempotent.
#
# WHY THIS EXISTS
# ---------------
# Each repo's .git/hooks/pre-commit announced itself as "Auto-installed by
# epyc-root" — but no installer existed in tracked code in any of the three
# repos. The wrapper was untracked working-tree state, so:
#
#   * a fresh clone had NO pre-commit hook at all, silently;
#   * a fix applied to one wrapper reached only that one checkout;
#   * nothing could review or diff the wrappers, because they were in no repo.
#
# That is how the 2026-08-03 status-propagation defect survived: epyc-root and
# epyc-orchestrator both called their hooks BARE, so the wrapper exited with the
# status of the LAST hook and a failing pii_precommit.sh was discarded by a
# passing hermes_drift_precommit.sh. Reproduced with a real AWS key staged: the
# hook printed "BLOCKED: [secret] AWS secret access key" and the commit landed.
# Every secret pattern was advisory-only in two of three repos.
#
# CONTRACT OF THE GENERATED WRAPPER
#   1. Run ALL shared hooks — never stop at the first failure, or one hook's
#      findings hide another's.
#   2. Accumulate status; exit non-zero if ANY hook failed.
#      Deliberately NOT `|| exit $?`, which short-circuits (see 1).
#   3. Source an optional per-repo extras file if present, so repo-specific
#      checks are NOT clobbered by re-running this installer. Extras use the
#      same `status=1` accumulation.
#
# Verified end-to-end by scripts/hooks/tests/test_precommit_wrapper.sh, which
# drives each INSTALLED wrapper against a throwaway repo with a known-bad blob
# and asserts non-zero, and against a clean set and asserts zero (so a wrapper
# cannot pass by always failing).
#
# Usage:  bash scripts/hooks/install_git_hooks.sh [--check]
#         --check  verify without writing; non-zero if any repo is wrong.

HOOK_SRC_DIR="/workspace/scripts/hooks"
REPOS=(
  "/workspace"
  "/mnt/raid0/llm/epyc-orchestrator"
  "/mnt/raid0/llm/epyc-inference-research"
)

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

emit_wrapper() {
  cat <<WRAPPER
#!/bin/bash
# GENERATED by epyc-root scripts/hooks/install_git_hooks.sh — do not hand-edit.
# Repo-specific checks belong in .git/hooks/pre-commit.extras (sourced below),
# which this installer never overwrites.
#
# STATUS PROPAGATION IS LOAD-BEARING. Run every hook, accumulate, fail if any
# failed. Do NOT revert to bare calls (status silently discarded) and do NOT use
# \`|| exit \$?\` (stops at the first failure, hiding the rest).
status=0
"${HOOK_SRC_DIR}/pii_precommit.sh" "\$@" || status=1
"${HOOK_SRC_DIR}/hermes_drift_precommit.sh" "\$@" || status=1

# Per-repo extras. Must accumulate into \$status, not exit directly.
if [[ -r "\$(dirname "\$0")/pre-commit.extras" ]]; then
    # shellcheck disable=SC1091
    source "\$(dirname "\$0")/pre-commit.extras"
fi

exit "\$status"
WRAPPER
}

rc=0
for repo in "${REPOS[@]}"; do
  hook="${repo}/.git/hooks/pre-commit"
  if [[ ! -d "${repo}/.git" ]]; then
    # A worktree has .git as a FILE; resolve it rather than skipping silently.
    if [[ -f "${repo}/.git" ]]; then
      gitdir="$(git -C "$repo" rev-parse --git-common-dir 2>/dev/null || true)"
      [[ -n "$gitdir" ]] && hook="${gitdir}/hooks/pre-commit"
    else
      echo "  SKIP ${repo} — not a git repo"
      continue
    fi
  fi

  desired="$(emit_wrapper)"
  if [[ -f "$hook" ]] && [[ "$(cat "$hook")" == "$desired" ]]; then
    echo "  ok   ${repo}"
    continue
  fi

  if (( CHECK_ONLY )); then
    echo "  WRONG ${repo} — wrapper differs from the generated contract"
    rc=1
    continue
  fi

  mkdir -p "$(dirname "$hook")"
  if [[ -f "$hook" ]]; then
    cp "$hook" "${hook}.bak-$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  fi
  printf '%s\n' "$desired" > "$hook"
  chmod +x "$hook"
  echo "  installed ${repo}"
done

exit "$rc"
