#!/bin/bash
set -euo pipefail
# Install the pre-commit wrapper into every owned repo. Idempotent.
#
# WHY THIS EXISTS
# ---------------
# Each repo's .git/hooks/pre-commit announced itself as "Auto-installed by
# epyc-root" — but no installer existed in tracked code in any of the three
# repos. The wrapper was untracked working-tree state, so:
#
#   * a fresh clone had NO pre-commit hook at all, silently;
#   * a fix applied to one wrapper reached only that one checkout;
#   * nothing could review or diff the wrappers, because they were in no repo.
#
# That is how the 2026-08-03 status-propagation defect survived: epyc-root and
# epyc-orchestrator both called their hooks BARE, so the wrapper exited with the
# status of the LAST hook and a failing pii_precommit.sh was discarded by a
# passing hermes_drift_precommit.sh. Reproduced with a real AWS key staged: the
# hook printed "BLOCKED: [secret] AWS secret access key" and the commit landed.
# Every secret pattern was advisory-only in two of three repos.
#
# CONTRACT OF THE GENERATED WRAPPER
#   1. Run ALL shared hooks — never stop at the first failure, or one hook's
#      findings hide another's.
#   2. Accumulate status; exit non-zero if ANY hook failed.
#      Deliberately NOT `|| exit $?`, which short-circuits (see 1).
#   3. Source an optional per-repo extras file if present. Extras use the same
#      `status=1` accumulation. A repo that VERSIONS its extras at
#      scripts/hooks/pre-commit.extras has that tracked file installed over the
#      local one (added 2026-08-04 — `.git/` reaches no clone, so an extras file
#      that exists only there is a one-host artifact, which is the very defect
#      this installer was written to fix for the wrapper). A repo that tracks no
#      extras keeps whatever local extras it has, un-clobbered, as before.
#
# Verified end-to-end by scripts/hooks/tests/test_precommit_wrapper.sh, which
# drives each INSTALLED wrapper against a throwaway repo with a known-bad blob
# and asserts non-zero, and against a clean set and asserts zero (so a wrapper
# cannot pass by always failing).
#
# Usage:  bash scripts/hooks/install_git_hooks.sh [--check]
#         --check  verify without writing; non-zero if any repo is wrong.
#
# WORKTREE CORRECTNESS (2026-08-12, guard-universe-and-worktree-isolation P1/3a)
# ------------------------------------------------------------------------------
# `.git/hooks/` is SHARED across a repo and every one of its worktrees — a
# worktree's `.git` is a file pointing at the common store, and
# `git rev-parse --git-path hooks` from inside one resolves to the SAME
# `/workspace/.git/hooks` every other worktree uses (verified: run it from
# /workspace/worktrees/mainA). So there is exactly one emitted pre-commit
# file, shared by every worktree, and it must work out AT RUNTIME which
# worktree is committing — it cannot know that at generation time.
#
# The emitted wrapper therefore no longer has HOOK_SRC_DIR baked in as a
# generation-time literal (the old body interpolated the installer's own
# ${HOOK_SRC_DIR} into the heredoc, so every installed wrapper — in every
# repo, from every worktree — carried the SAME literal "/workspace/scripts/
# hooks" regardless of who was committing). It now resolves its own
# HOOK_SRC_DIR each time it runs via `git rev-parse --show-toplevel` — the
# committing worktree's own root — falling back to the git-common-dir's
# primary tree when that worktree has no scripts/hooks of its own (a sparse
# worktree checkout). This mirrors scripts/handoffs/install_timeline_hook.sh,
# whose post-commit/post-merge/post-checkout hooks already resolve their repo
# root the same way (`git -C "$(dirname "$0")" rev-parse --show-toplevel`)
# rather than baking in a path at install time.

REPOS=(
  "/workspace"
  "/mnt/raid0/llm/epyc-orchestrator"
  "/mnt/raid0/llm/epyc-inference-research"
)

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

emit_wrapper() {
  # Fully-quoted heredoc delimiter ('WRAPPER'): nothing in this body is
  # expanded at generation time — HOOK_SRC_DIR is resolved by the emitted
  # script itself, at hook-execution time, not baked in here. That is the
  # whole worktree-correctness fix; see the header comment above.
  cat <<'WRAPPER'
#!/bin/bash
# GENERATED by epyc-root scripts/hooks/install_git_hooks.sh — do not hand-edit.
# Repo-specific checks belong in .git/hooks/pre-commit.extras (sourced below).
# Version them at <repo>/scripts/hooks/pre-commit.extras: the installer copies a
# tracked source over this file, and a hand-written .git/hooks/pre-commit.extras
# reaches no clone. Repos that track no extras keep their local file untouched.
#
# STATUS PROPAGATION IS LOAD-BEARING. Run every hook, accumulate, fail if any
# failed. Do NOT revert to bare calls (status silently discarded) and do NOT use
# `|| exit $?` (stops at the first failure, hiding the rest).
#
# HOOK_SRC_DIR IS RESOLVED HERE, AT RUNTIME — never baked in at install time,
# tried in order, first real match wins:
#
#   1. EPYC_HOOK_SRC_DIR override, for tests only (mirrors EPYC_BUS_ROOT in
#      scripts/coordination/session_bus.py::get_bus_root). Production commits
#      never set it. It exists because a test driving this installed file
#      end-to-end (scripts/hooks/tests/test_precommit_wrapper.sh) does so
#      from a throwaway sandbox repo with no relationship to any real
#      checkout, where git-plumbing resolution has nothing correct to find;
#      the override lets that test supply the real scripts/hooks dir.
#   2. The COMMITTING worktree's own scripts/hooks/, if it actually has the
#      hook scripts checked out. .git/hooks/ is shared by every worktree of a
#      repo, so this exact file runs for a commit made in ANY of them — this
#      is the fix: ask git which worktree is committing right now and prefer
#      ITS checkout (so a worktree testing a hook change sees its own edit).
#   3. The git-common-dir's primary tree (the canonical checkout every
#      worktree's .git file points back to) — covers a sparse worktree that
#      omitted scripts/.
#   4. Literal /workspace/scripts/hooks, last resort. This is NOT the old bug
#      reintroduced: the old wrapper used this path UNCONDITIONALLY, baked in
#      at generation time, for every repo and every worktree. This is reached
#      only when tiers 2-3 found no real checkout of the scripts — which is
#      the case, BY DESIGN, for the sibling repos (epyc-orchestrator,
#      epyc-inference-research): they have never carried their own copy of
#      these shared governance hooks and have no git-worktree relationship to
#      epyc-root through which to discover its location, so there is no
#      git-plumbing answer to fall back to. Verified empirically 2026-08-12:
#      neither repo has scripts/hooks/pii_precommit.sh on disk.
if [[ -n "${EPYC_HOOK_SRC_DIR:-}" ]]; then
    HOOK_SRC_DIR="$EPYC_HOOK_SRC_DIR"
else
    HOOK_SRC_DIR=""
    repo="$(git rev-parse --show-toplevel 2>/dev/null)"
    if [[ -n "$repo" && -f "${repo}/scripts/hooks/pii_precommit.sh" ]]; then
        HOOK_SRC_DIR="${repo}/scripts/hooks"
    fi
    if [[ -z "$HOOK_SRC_DIR" ]]; then
        common="$(git rev-parse --git-common-dir 2>/dev/null)"
        case "$common" in
            /*) : ;;                          # already absolute
            "") ;;                            # unresolvable — leave empty
            *)  common="${repo}/${common}" ;; # relative to the worktree root
        esac
        if [[ -n "$common" ]]; then
            primary="$(dirname "$common")"
            if [[ -f "${primary}/scripts/hooks/pii_precommit.sh" ]]; then
                HOOK_SRC_DIR="${primary}/scripts/hooks"
            fi
        fi
    fi
    if [[ -z "$HOOK_SRC_DIR" ]]; then
        HOOK_SRC_DIR="/workspace/scripts/hooks"
    fi
fi

status=0
"${HOOK_SRC_DIR}/pii_precommit.sh" "$@" || status=1
"${HOOK_SRC_DIR}/hermes_drift_precommit.sh" "$@" || status=1

# Per-repo extras. Must accumulate into $status, not exit directly.
if [[ -r "$(dirname "$0")/pre-commit.extras" ]]; then
    # shellcheck disable=SC1091
    source "$(dirname "$0")/pre-commit.extras"
fi

exit "$status"
WRAPPER
}

rc=0
for repo in "${REPOS[@]}"; do
  hook="${repo}/.git/hooks/pre-commit"
  if [[ ! -d "${repo}/.git" ]]; then
    # A worktree has .git as a FILE; resolve it rather than skipping silently.
    if [[ -f "${repo}/.git" ]]; then
      gitdir="$(git -C "$repo" rev-parse --git-common-dir 2>/dev/null || true)"
      [[ -n "$gitdir" ]] && hook="${gitdir}/hooks/pre-commit"
    else
      echo "  SKIP ${repo} — not a git repo"
      continue
    fi
  fi

  desired="$(emit_wrapper)"
  if [[ -f "$hook" ]] && [[ "$(cat "$hook")" == "$desired" ]]; then
    echo "  ok   ${repo}"
  elif (( CHECK_ONLY )); then
    echo "  WRONG ${repo} — wrapper differs from the generated contract"
    rc=1
  else
    mkdir -p "$(dirname "$hook")"
    if [[ -f "$hook" ]]; then
      cp "$hook" "${hook}.bak-$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    fi
    printf '%s\n' "$desired" > "$hook"
    chmod +x "$hook"
    echo "  installed ${repo}"
  fi

  # -- per-repo extras -------------------------------------------------------
  # Added 2026-08-04. A repo may VERSION its extras at scripts/hooks/pre-commit.extras;
  # if it does, that tracked file is the source of truth and is installed to
  # .git/hooks/pre-commit.extras, where the wrapper sources it.
  #
  # WHY. `.git/` is versioned by nothing. epyc-inference-research's evidence-durability
  # extras was hand-written straight into `.git/hooks/` on 2026-08-03: it worked on that
  # one host, no clone ever received it, and no review ever saw it — the same defect this
  # installer exists to fix for the wrapper (which announced "Auto-installed by epyc-root"
  # while no installer existed in tracked code), reintroduced one layer down.
  #
  # The no-clobber promise in the wrapper's header is NARROWED, not broken: a repo that
  # does not track an extras file still keeps whatever local extras it has, untouched.
  # Opting in by committing the file is what makes it managed. A local-only extras that
  # a repo later decides to version is meant to be replaced by the versioned copy —
  # otherwise the tracked file is decorative and the host stays the real policy.
  src_extras="${repo}/scripts/hooks/pre-commit.extras"
  dst_extras="$(dirname "$hook")/pre-commit.extras"
  [[ -f "$src_extras" ]] || continue

  if [[ -f "$dst_extras" ]] && cmp -s "$src_extras" "$dst_extras"; then
    echo "  ok   ${repo} — extras match the tracked source"
  elif (( CHECK_ONLY )); then
    echo "  WRONG ${repo} — .git/hooks/pre-commit.extras differs from ${src_extras#"$repo"/}"
    rc=1
  else
    if [[ -f "$dst_extras" ]]; then
      cp "$dst_extras" "${dst_extras}.bak-$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    fi
    # Write-then-rename: a commit in another session may be sourcing this file right
    # now, and rename is atomic on the same filesystem while `>` is not.
    cp "$src_extras" "${dst_extras}.tmp.$$"
    mv -f "${dst_extras}.tmp.$$" "$dst_extras"
    echo "  installed ${repo} extras"
  fi
done

exit "$rc"
